services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: schedule_arranger
    volumes:
      - schedule-arranger-data:/var/lib/postgresql/data
volumes:
  node_modules:
  schedule-arranger-data:
    external: true
